version: 2
updates:
  # Monitor frontend (JavaScript/Node) dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  # Monitor backend (.NET/C#) dependencies
  - package-ecosystem: "nuget"
    directory: "/backend/ApplicationTracker"
    schedule:
      interval: "weekly"
