name: 🎯 Feature Request
description: Request a feature in this project
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered
      placeholder: What other approaches have you thought about?

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here
      placeholder: Any additional information, mockups, or screenshots...

  - type: checkboxes
    id: implementation-willingness
    attributes:
      label: Would you like to work on this feature?
      options:
        - label: Yes, I'd like to implement this feature
        - label: No, I'm just suggesting it