name: ⚙️ GitHub Request
description: Request an update to permissions/management/settings on the project GitHub organization or its repositories
title: "[GITHUB] "
labels: ["github"]
body:
  - type: checkboxes
    id: request-type
    attributes:
      label: Type of GitHub Request
      description: Select the type of request (check all that apply)
      options:
        - label: Repository settings change
        - label: Permission/access change
        - label: Branch protection rules
        - label: Repository creation/deletion
        - label: Organization settings
        - label: Other (please specify)
    validations:
      required: true

  - type: textarea
    id: request-description
    attributes:
      label: Describe the request
      description: A clear and concise description of what GitHub configuration change you need
      placeholder: Describe the specific GitHub configuration change you're requesting...
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: Justification
      description: Explain why this change is needed and how it benefits the project
      placeholder: Explain the reasoning and benefits of this change...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or links about the request here
      placeholder: Any additional information, screenshots, or relevant links...