name: 💡 Proposal
description: Suggest an idea for a specific feature you wish to propose to the community for comment
title: '[PROPOSAL] '
labels:
  - proposal
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief, clear summary of what you're proposing.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this change important? What problem does it solve? Who benefits from this proposal?
    validations:
      required: true
  - type: textarea
    id: detailed-design
    attributes:
      label: Detailed Design
      description: Provide a detailed explanation of how this would work.
      placeholder: |
        Include:
        - Technical approach
        - API changes (if applicable)
        - Implementation details
        - Examples of usage
    validations:
      required: true
  - type: textarea
    id: drawbacks
    attributes:
      label: Drawbacks
      description: What are the potential downsides or risks of this proposal?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: What other approaches have you considered? Why is this approach better?
  - type: textarea
    id: timeline
    attributes:
      label: Timeline
      description: If you have thoughts on implementation timeline or phases, include them here.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, research, links, or examples that support this proposal.